name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test calculator
      run: |
        coverage run -m pytest tests/test_calculator.py
        coverage xml
    - uses: codecov/codecov-action@v1
      with:
        flags: calculator
    - name: Test smiles
      run: |
        coverage run -m pytest tests/test_smiles.py
        coverage xml
    - uses: codecov/codecov-action@v1
      with:
        flags: smiles
